mixed-port: 7890
socks-port: 7891
bind-address: "*"
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
     - '*.lan'
     - localhost.ptlogin2.qq.com
  nameserver:
     - 114.114.114.114 
     - 223.5.5.5 
     - 119.29.29.29 
     - 180.76.76.76
     - 117.50.11.11
     - 117.50.10.10
     - https://dns.alidns.com/dns-query
     - tls://dns.alidns.com
     - https://doh.360.cn/dns-query
     - https://doh.pub/dns-query
     - tls://dot.pub
  fallback:
     - https://dns.google/dns-query
     - tls://dns.google:853
     - https://cloudflare-dns.com/dns-query
     - tls://1.0.0.1:853
     - https://dns.rubyfish.cn/dns-query
     - tls://dns.rubyfish.cn:853
  fallback-filter:
     geoip: true
     ipcidr:
       - 0.0.0.0/8
       - 10.0.0.0/8
       - 100.64.0.0/10
       - 127.0.0.0/8
       - 169.254.0.0/16
       - 172.16.0.0/12
       - 192.0.0.0/24
       - 192.0.2.0/24
       - 192.88.99.0/24
       - 192.168.0.0/16
       - 198.18.0.0/15
       - 198.51.100.0/24
       - 203.0.113.0/24
       - 224.0.0.0/4
       - 240.0.0.0/4
       - 255.255.255.255/32
     domain:
       - +.google.com
       - +.facebook.com
       - +.youtube.com
       - +.githubusercontent.com
       - +.googlevideo.com
       - +.msftconnecttest.com
       - +.msftncsi.com
       - msftconnecttest.com
       - msftncsi.com
